service: applyindia-backend
frameworkVersion: "4"
useDotenv: true

plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

  deploymentBucket:
    name: applyindia-serverless-deployments-ap-south-1

  environment:
    APP_ENV: ${self:provider.stage}   # dev / prod
    RUNTIME_ENV: lambda               # THIS IS THE KEY
    DYNAMODB_TABLE_NAME: ${env:DYNAMODB_TABLE_NAME}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}

  httpApi:
    cors: true

    authorizers:
      cognitoJwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${env:COGNITO_USER_POOL_ID}
        audience:
          - ${env:COGNITO_CLIENT_ID}

custom:
  domains:
    dev: dev.applyindia.online
    prod: applyindia.online

  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: regional
    apiType: http
    securityPolicy: tls_1_2

functions:
  public:
    handler: dist/lambda.handler
    events:
      - httpApi:
          path: /public/{proxy+}
          method: ANY

  private:
    handler: dist/lambda.handler
    events:
      - httpApi:
          path: /api/{proxy+}
          method: ANY
          authorizer:
            name: cognitoJwtAuthorizer
